model:
  name: unsloth/llama-3-8b-bnb-4bit

output:
  dir: checkpoint

data:
  train_path: sample_data/train.csv
  test_path: sample_data/test.csv
  label_map_path: sample_data/label_map.json

training:
  max_seq_length: 512
  batch_size: 4
  epochs: 1
